site_url: https://wodatlenisen.site
display_url: https://wodatlenisen.site

backend:
  name: github
  repo: ArekCoachStoik/blog
  base_url: https://sveltia-cms-auth.korba-adam.workers.dev/

media_folder: static/images
public_folder: /images
locale: pl
show_preview_links: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string'}
      - {label: 'Featured image', name: 'featured_image', widget: 'image'}
      - {label: 'Body', name: 'body', widget: 'markdown'}

  - name: 'fraszka'
    label: 'Pro-Fraszka'
    folder: 'content/fraszka'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Description', name: 'description', widget: 'string'}
      - {label: 'Featured image', name: 'featured_image', widget: 'image'}
      - {label: 'Body', name: 'body', widget: 'markdown'}

